#!/usr/bin/env bash

cd ~
ipython profile create nbserver

echo "# Configuration file for ipython-notebook.
c = get_config()

import os
home = os.path.expanduser('~')

# Notebook config
c.NotebookApp.ip = '*'
c.NotebookApp.open_browser = False
# It is a good idea to put it on a known, fixed port
c.NotebookApp.port = 9999
c.IPKernelApp.pylab = 'inline' " >> ~/.ipython/profile_nbserver/ipython_notebook_config.py

echo 'export IPYTHON_OPTS="notebook --profile=nbserver"' >> ~/.bash_profile

source ~/.bash_profile

echo -e "\n\n\n"
echo "------------------------------------------------------------------------"
echo "iPython notebook successfully set up!"
echo "After starting a cluster, access at https://<ip address of driver>:9999"
echo "------------------------------------------------------------------------"
echo -e "\n\n\n"
