#!/usr/bin/env bash

cd ~
jupyter notebook --generate-config

echo "# Configuration file for jupyter-notebook.
c = get_config()

import os
home = os.path.expanduser('~')

# Notebook config
c.NotebookApp.ip = '*'
c.NotebookApp.open_browser = False
# It is a good idea to put it on a known, fixed port
c.NotebookApp.port = 9999" >> ~/.jupyter/jupyter_notebook_config.py

source ~/.bash_profile

echo -e "\n\n\n"
echo "------------------------------------------------------------------------"
echo "Jupyter notebook successfully set up!"
echo "------------------------------------------------------------------------"
echo -e "\n\n\n"
