#!/usr/local/python-2.7.6/bin/python2.7

import os
import glob
import sys
import argparse
import subprocess

parser = argparse.ArgumentParser(description="setup and run thunder")

parser.add_argument("task", choices=('install', 'update', 'start'), default='start')
parser.add_argument("-v", "--sparkversion", type=str, default='1', required=False)
parser.add_argument("-i", "--ipython", action="store_true")
parser.add_argument("-l", "--thunderpath", type=str, default='~/thunder', required=False)

args = parser.parse_args()

SPARKVERSIONS = {
    '1': '/usr/local/spark-current',
    '2': '/usr/local/spark-master',
    '3': '/usr/local/spark-test'
}

if not args.thunderpath[0] in set(('/','~')):
    location  = os.getcwd() + '/' + args.thunderpath
else:
    location = args.thunderpath
location  = os.path.expanduser(location)

if args.task == 'install':
   
    if os.getenv('PATH') is None:
       os.environ['PATH'] = ""
    os.environ['PATH'] = os.environ['PATH'] + ":" + "/usr/local/python-2.7.6/bin"

    if os.path.exists(location):
    	print('\n')
        print >> sys.stderr, "thunder already exists, run with 'update' to update installation"
        print('\n')
    else:
    	os.system('git clone git://github.com/freeman-lab/thunder.git ' + location)
    	subprocess.call(location + '/python/bin/build')
    	print('\n')
    	print("thunder installed to " + args.thunderpath)
    	print('\n')

if args.task == 'update':
  
    if os.getenv('PATH') is None:
       os.environ['PATH'] = ""
    os.environ['PATH'] = os.environ['PATH'] + ":" + "/usr/local/python-2.7.6/bin"

    cwd = os.getcwd()
    if not os.path.exists(location):
    	print('\n')
        print >> sys.stderr, "cannot find thunder installation in " + args.thunderpath + ", try running install first"
        print('\n')
    else:
	    os.chdir(location)
	    os.system('git pull')
	    subprocess.call(location + '/python/bin/build')
	    os.chdir(cwd)
	    print('\n')
	    print("thunder is up-to-date and rebuilt")
	    print('\n')

if args.task == 'start':
    
    if args.ipython is True:
       os.environ['IPYTHON_OPTS'] = "notebook --profile=nbserver"

    os.environ['SPARK_HOME'] = SPARKVERSIONS[args.sparkversion]

    if os.getenv('PYTHONPATH') is None:
        os.environ['PYTHONPATH'] = ""
    os.environ['PYTHONPATH'] = os.environ['PYTHONPATH'] + ":" + location + "/python/"
  
    if os.getenv('PATH') is None:
        os.environ['PATH'] = ""

    if os.getenv('IPYTHON') is None:
       os.environ['IPYTHON'] = "1"

    os.environ['PATH'] = os.environ['PATH'] + ":" + location + "/python/bin"
    os.environ['PATH'] = os.environ['PATH'] + ":" + "/usr/local/python-2.7.6/bin"
    f = open(os.path.expanduser("~") + '/spark-master', 'r')
    os.environ['MASTER'] = f.readline().replace('\n','')
    os.system(location + '/python/bin/thunder')
