#!/usr/local/python-2.7.6/bin/python2.7

import os
import glob
import sys
import argparse
import subprocess

parser = argparse.ArgumentParser(description="setup and run thunder")

parser.add_argument("task", choices=('install', 'update', 'start'), default='start')
parser.add_argument("-v", "--sparkversion", type=str, choices=('stable', 'rc', 'test'), default='stable', required=False)
parser.add_argument("-i", "--ipython", action="store_true")
parser.add_argument("-p", "--thunderpath", type=str, default='~/thunder', required=False)

args = parser.parse_args()

SPARKVERSIONS = {   
    'stable': '/usr/local/spark-current/',
    'rc': '/usr/local/spark-rc/',
    'test': '/usr/local/spark-test'
} 

location = os.path.realpath(os.path.expanduser(args.thunderpath))

if args.task == 'install':
   
    if os.getenv('PATH') is None:
       os.environ['PATH'] = ""
    os.environ['PATH'] = os.environ['PATH'] + ":" + "/usr/local/python-2.7.6/bin"

    if os.getenv('PYTHONPATH') is None:
        os.environ['PYTHONPATH'] = ""
    os.environ['PYTHONPATH'] = os.environ['PYTHONPATH'] + ":" + location + "/python/"

    if os.path.exists(location):
    	print('\n')
        print >> sys.stderr, "thunder already exists, run with 'update' to update installation"
        print('\n')
    else:
    	os.system('git clone git://github.com/freeman-lab/thunder.git ' + location)
    	subprocess.call(location + '/python/bin/build')
    	print('\n')
    	print("thunder installed to " + args.thunderpath)
    	print('\n')

if args.task == 'update':
  
    if os.getenv('PATH') is None:
       os.environ['PATH'] = ""
    os.environ['PATH'] = os.environ['PATH'] + ":" + "/usr/local/python-2.7.6/bin"

    if os.getenv('PYTHONPATH') is None:
        os.environ['PYTHONPATH'] = ""
    os.environ['PYTHONPATH'] = os.environ['PYTHONPATH'] + ":" + location + "/python/"

    cwd = os.getcwd()
    if not os.path.exists(location):
    	print('\n')
        print >> sys.stderr, "cannot find thunder installation in " + args.thunderpath + ", try running install first"
        print('\n')
    else:
	    os.chdir(location)
	    os.system('git pull')
	    subprocess.call(location + '/python/bin/build')
	    os.chdir(cwd)
	    print('\n')
	    print("thunder is up-to-date and rebuilt")
	    print('\n')

if args.task == 'start':
    
    f = open(os.path.expanduser("~") + '/spark-master', 'r')
    master = f.readline().replace('\n','')

    if args.ipython is True:
       os.environ['IPYTHON_OPTS'] = "notebook --profile=nbserver"
       status = master[8:][:-5]
       print('\n')
       print('View your notebooks at http://' + os.environ['HOSTNAME'] + ':9999')
       print('View the status of your cluster at http://' + status + ':8080')
       print('\n')

    os.environ['SPARK_HOME'] = SPARKVERSIONS[args.sparkversion]

    if os.getenv('PYTHONPATH') is None:
        os.environ['PYTHONPATH'] = ""
    os.environ['PYTHONPATH'] = os.environ['PYTHONPATH'] + ":" + location + "/python/"
  
    if os.getenv('PATH') is None:
        os.environ['PATH'] = ""

    if os.getenv('IPYTHON') is None:
       os.environ['IPYTHON'] = "1"

    os.environ['PATH'] = os.environ['PATH'] + ":" + location + "/python/bin"
    os.environ['PATH'] = os.environ['PATH'] + ":" + "/usr/local/python-2.7.6/bin"
    
    os.environ['MASTER'] = master
    os.system(location + '/python/bin/thunder')
